### ISSUE TITLE
After opening a file that I was just previewing, the Search highlight persists

### ISSUE THREAD

**Issue by joeytwiddle** [ronakg/quickr-preview.vim#10]

**Comment by matt1003** [comment]
This is meant to be cleaned up by the following code:
``` vim
function! QuickrPreviewExit()
    pclose!
    execute 'sign unplace 26'
endfunction

function! QuickrPreviewSetupExit()
    if &buftype == 'quickfix'
        autocmd BufDelete <buffer> call QuickrPreviewExit()
    endif
endfunction

augroup quickfix_cmds
    autocmd!
    autocmd BufCreate * call QuickrPreviewSetupExit()
augroup END
```

Can you confirm whether the `BufDelete` auto command is being triggered?

**Comment by ronakg** [comment]
`BufDelete` should be getting triggered.

**Comment by matt1003** [comment]
Sorry, ignore my previous comment. That will only work when closing/deleting the quickfix buffer, rather then when opening a file that was being previewed.

Commit ed3b58d570841e0dc562ae98659e74c99bea14d3 will resolve this issue for unlisted buffers. I'll create another commit for listed buffers.

**Comment by joeytwiddle** [comment]
Tested it here, and the issue is no longer occurring. Fantastic work!
